sudo: required
services:
  - docker

before_install:
  - docker build -t erindmehmeti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erindmehmeti/docker-react npm run test -- --coverage