sudo: required
services:
  - docker

before_install:
  - docker build -t erindmehmeti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erindmehmeti/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-eu-central-1-556395405627"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"